# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bK-qIsOKzbzVMBz0SKbm4fpoAGbh3Ybx
"""

import pandas as pd
avazbek={
   "Fish":[ "Aliyev Ali","Aliyeva Aliya","Valiyev Ali","Valiyeva Rano","Aliyeva Vali","Ganiyev Sher","Ahmedov Jasur","Omonov Javlon","Jorayev Aziz","Sodiqova Aziza"  ],
   "Yoshi":[ '11','15','16','71','19','21','22','43','27','67'  ],
   "Maktabi":['49-maktab','53-maktab','21-maktab','24-maktab','43-maktab','51-maktab','17-maktab','37-maktab','6-maktab','8-maktab' ],
   "Jinsi":['erkak','ayol','erkak','ayol','erkak','erkak','erkak','erkak','erkak','ayol'],
   "Manzili":["fargona shahar","toahkent shahar","qoqon shahar","andijon shahar","namangan shahar","buxoro shahar","oltiariq shahar","yangiyolshahar","quva shahar","kirgili shahar"]
}
malumot=pd.DataFrame(avazbek)
print(malumot)

filtr=malumot[(malumot["Jinsi"]=='erkak') & (malumot["Yoshi"] >"15" ) & (malumot["Manzili"] == "qoqon shahar")]
print(filtr)